use_frameworks!
platform :ios, "8.0"

target 'SwiftDataProvider_Example' do
  pod 'SwiftDataProvider', :path => '../'
end

target 'LoginExample' do
  pod 'SwiftDataProvider', :path => '../'
end

target 'SelectTimeExample' do
    pod 'SwiftDataProvider', :path => '../'
end
