language: swift
osx_image: xcode10
matrix:
  include:
    - osx_image: xcode10
      env: PLATFORM="iOS"
cache:
  - bundler
before_install:
  - brew update
script:
  - bundle exec rake ci[$PLATFORM]
after_success:
  - bash <(curl -s https://codecov.io/bash)
